#!/usr/bin/env python3
"""Parse Firedancer fd_poseidon_params.c (Fr-Montgomery form) and emit a Zig
params file in NORMAL (non-Montgomery) form. normal = mont * R^-1 mod r.

The conversion is validated end-to-end by the differential gate (the poseidon
output must match Firedancer/solana byte-for-byte), so a wrong constant fails
loudly rather than silently forking."""
import re, sys

# Adjust to your local Firedancer checkout before running.
SRC = "firedancer/src/ballet/bn254/fd_poseidon_params.c"
OUT = "src/vex_crypto/bn254/poseidon_params.zig"

r = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001
R = (1 << 256) % r
R_inv = pow(R, -1, r)

def to_normal(mont):
    return (mont * R_inv) % r

txt = open(SRC).read()

# Grab each array body: static const fd_bn254_scalar_t NAME[] = { ... };
arrays = {}
for m in re.finditer(r'fd_bn254_scalar_t\s+(fd_poseidon_(?:ark|mds)_\d+)\[\]\s*=\s*\{(.*?)\n\};', txt, re.S):
    name, body = m.group(1), m.group(2)
    vals = []
    for lm in re.finditer(r'\{\{\s*([^}]*?)\s*\}\}', body):
        limbs = [int(x, 16) for x in re.findall(r'0x[0-9a-fA-F]+', lm.group(1))]
        assert len(limbs) == 4, (name, lm.group(1))
        mont = limbs[0] | (limbs[1] << 64) | (limbs[2] << 128) | (limbs[3] << 192)
        vals.append(to_normal(mont))
    arrays[name] = vals

# Sanity: ark_2 must be 128 entries (64 rounds * width 2), mds_2 = 4.
assert len(arrays['fd_poseidon_ark_2']) == 128, len(arrays['fd_poseidon_ark_2'])
assert len(arrays['fd_poseidon_mds_2']) == 4

def emit_array(name, vals):
    out = [f"pub const {name} = [_]u256{{"]
    line = "    "
    for i, v in enumerate(vals):
        tok = f"0x{v:064x}, "
        if len(line) + len(tok) > 110:
            out.append(line.rstrip())
            line = "    "
        line += tok
    if line.strip():
        out.append(line.rstrip())
    out.append("};")
    return "\n".join(out)

with open(OUT, "w") as f:
    f.write("//! Vexor Poseidon-BN254 round constants (ark) + MDS matrices, widths 2..13.\n")
    f.write("//!\n")
    f.write("//! Generated by scratchpad/gen_poseidon_params.py from Firedancer\n")
    f.write("//! fd_poseidon_params.c, converted OUT of Fr-Montgomery form to normal\n")
    f.write("//! residues (normal = mont * R^-1 mod r). The upstream constants originate\n")
    f.write("//! from light-poseidon v0.2.0 / circomlib v2.0.5 (bn254_x5). Correctness of\n")
    f.write("//! the conversion is proven end-to-end by the differential gate against the\n")
    f.write("//! Firedancer/solana poseidon vectors. Credited in src/vex_crypto/NOTICE.\n\n")
    for w in range(2, 14):
        f.write(emit_array(f"fd_poseidon_ark_{w}", arrays[f"fd_poseidon_ark_{w}"]) + "\n\n")
    for w in range(2, 14):
        f.write(emit_array(f"fd_poseidon_mds_{w}", arrays[f"fd_poseidon_mds_{w}"]) + "\n\n")
    # dispatch tables
    f.write("pub const ark = [_][]const u256{\n")
    for w in range(2, 14):
        f.write(f"    &fd_poseidon_ark_{w},\n")
    f.write("};\n\n")
    f.write("pub const mds = [_][]const u256{\n")
    for w in range(2, 14):
        f.write(f"    &fd_poseidon_mds_{w},\n")
    f.write("};\n")

print("wrote", OUT)
for w in range(2, 14):
    print(f"width {w}: ark={len(arrays[f'fd_poseidon_ark_{w}'])} mds={len(arrays[f'fd_poseidon_mds_{w}'])}")
